=== flyingsl0ths/Lazy-Text-Editor/src/main/resources/themes/theme.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT LazyTextTheme (window, customcomponents?)>

<!ELEMENT window (baseFont?, menuBar, findTextMenu, 
themeChooserMenu, textAreaScrollBars, lineNumberArea, textArea, statusBar)>

<!ELEMENT baseFont EMPTY>
<!ELEMENT menuBar EMPTY>
<!ELEMENT findTextMenu EMPTY>
<!ELEMENT themeChooserMenu EMPTY>
<!ELEMENT textAreaScrollBars EMPTY>
<!ELEMENT lineNumberArea EMPTY>
<!ELEMENT textArea EMPTY>
<!ELEMENT statusBar EMPTY>

<!ELEMENT customcomponents (components)*>
<!ELEMENT components (#PCDATA)>


<!ATTLIST baseFont
    family CDATA #IMPLIED
    fontSize CDATA #IMPLIED
>

<!ATTLIST menuBar
    fgColor CDATA #REQUIRED
    bgColor CDATA #REQUIRED
>

<!ATTLIST findTextMenu
    bgColor CDATA #REQUIRED
>

<!ATTLIST themeChooserMenu
    fgColor CDATA #REQUIRED
    bgColor CDATA #REQUIRED
>

<!ATTLIST textAreaScrollBars
    thmbColor CDATA #REQUIRED
    bgColor CDATA #IMPLIED
    scrollBarWidth CDATA #IMPLIED
>

<!ATTLIST lineNumberArea
    fgColor CDATA #REQUIRED
    bgColor CDATA #IMPLIED
>

<!ATTLIST textArea
    fgColor CDATA #REQUIRED
    bgColor CDATA #REQUIRED
    caretColor CDATA #IMPLIED
>

<!ATTLIST statusBar
    fgColor CDATA #REQUIRED
    bgColor CDATA #REQUIRED
>

<!ATTLIST components
    fgColor CDATA #REQUIRED
    bgColor CDATA #REQUIRED
>

=== flyingsl0ths/Lazy-Text-Editor/src/main/resources/themes/Monokai.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LazyTextTheme SYSTEM "theme.dtd">

<LazyTextTheme>
    <window>
        <baseFont family="Sans-Serif" fontSize="26"/>
        <menuBar fgColor="#f8f8f2" bgColor="#1E1F1C"/>
        <findTextMenu bgColor="#1E1F1C"/>
        <themeChooserMenu fgColor="#f8f8f2" bgColor="#1E1F1C"/>
        <textAreaScrollBars thmbColor="#474844" bgColor="#272822"/>
        <lineNumberArea fgColor="#f8f8f2" bgColor="#272822"/>
        <textArea fgColor="#f8f8f2" bgColor="#272822" caretColor="#f8f8f2"/>
        <statusBar fgColor="#f8f8f2" bgColor="#414339"/>
    </window>
</LazyTextTheme>

=== flyingsl0ths/Lazy-Text-Editor/src/main/resources/themes/Dark.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LazyTextTheme SYSTEM "theme.dtd">

<LazyTextTheme>
    <window>
        <baseFont family="Sans-Serif" fontSize="26"/>
        <menuBar fgColor="#BDBDBD" bgColor="#424242"/>
        <findTextMenu bgColor="#424242"/>
        <themeChooserMenu fgColor="#BDBDBD" bgColor="#424242"/>
        <textAreaScrollBars thmbColor="#BDBDBD" bgColor="#212121"/>
        <lineNumberArea fgColor="#BDBDBD" bgColor="#212121"/>
        <textArea fgColor="#BDBDBD" bgColor="#212121" caretColor="#BDBDBD"/>
        <statusBar fgColor="#BDBDBD" bgColor="#424242"/>
    </window>
</LazyTextTheme>

=== flyingsl0ths/Lazy-Text-Editor/src/main/resources/themes/Light.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LazyTextTheme SYSTEM "theme.dtd">

<LazyTextTheme>
    <window>
        <baseFont family="Sans-Serif" fontSize="26"/>
        <menuBar fgColor="#212121" bgColor="#EEEEEE"/>
        <findTextMenu bgColor="#EEEEEE"/>
        <themeChooserMenu fgColor="#000000" bgColor="#E0E0E0"/>
        <textAreaScrollBars thmbColor="#CCCCCC" bgColor="#EEEEEE"/>
        <lineNumberArea fgColor="#212121" bgColor="#ffffff"/>
        <textArea fgColor="#212121" bgColor="#ffffff" caretColor="#212121"/>
        <statusBar fgColor="#212121" bgColor="#EEEEEE"/>
    </window>
    <customcomponents>
    </customcomponents>
</LazyTextTheme>

=== flyingsl0ths/Lazy-Text-Editor/github_res/new_theme_template.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LazyTextTheme SYSTEM "theme.dtd">

<LazyTextTheme>
    <window>
        <baseFont family=" " fontSize=" "/>
        <menuBar fgColor=" " bgColor=" "/>
        <findTextMenu bgColor=" "/>
        <themeChooserMenu fgColor=" " bgColor=" "/>
        <textAreaScrollBars thmbColor=" " bgColor=" "/>
        <lineNumberArea fgColor=" " bgColor=" "/>
        <textArea fgColor=" " bgColor=" " caretColor=" "/>
    <statusBar fgColor=" " bgColor=" "/>
    </window>
    <customcomponents>
        <component fgColor=" " bgColor=" ">"Component Name"</component>
    </customcomponents>
</LazyTextTheme>
